import { Vehicle } from './types';

export const seedVehicles: Omit<Vehicle, '_id'>[] = [
    {
        make: 'BMW',
        model: 'X5 M Sport',
        year: 2023,
        price: 67900,
        mileage: 12500,
        bodyType: 'SUV',
        transmission: 'Automatic',
        fuelType: 'Gasoline',
        drivetrain: 'AWD',
        exteriorColor: 'Carbon Black',
        interiorColor: 'Black Leather',
        engine: '3.0L Inline-6 Turbo',
        horsepower: 335,
        description: 'Premium luxury SUV with M Sport package. Loaded with features including panoramic sunroof, Harman Kardon sound system, and advanced driver assistance.',
        features: ['Panoramic Sunroof', 'Leather Seats', 'Navigation System', 'Backup Camera', 'Heated Seats', 'Apple CarPlay', 'Adaptive Cruise Control'],
        images: [
            'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format',
            'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&auto=format'
        ],
        isFeatured: true,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        make: 'Mercedes-Benz',
        model: 'C-Class C300',
        year: 2024,
        price: 54900,
        mileage: 5200,
        bodyType: 'Sedan',
        transmission: 'Automatic',
        fuelType: 'Gasoline',
        drivetrain: 'RWD',
        exteriorColor: 'Polar White',
        interiorColor: 'Black',
        engine: '2.0L Inline-4 Turbo',
        horsepower: 255,
        description: 'Elegant and sophisticated sedan with cutting-edge technology and luxurious comfort.',
        features: ['MBUX Infotainment', 'LED Headlights', 'Wireless Charging', 'Keyless Entry', 'Ambient Lighting', 'Burmester Sound System'],
        images: [
            'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&auto=format',
            'https://images.unsplash.com/photo-1617531653520-e4f60be469df?w=800&auto=format'
        ],
        isFeatured: true,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        make: 'Ford',
        model: 'F-150 Raptor',
        year: 2023,
        price: 72500,
        mileage: 18000,
        bodyType: '4x4',
        transmission: 'Automatic',
        fuelType: 'Gasoline',
        drivetrain: '4WD',
        exteriorColor: 'Velocity Blue',
        interiorColor: 'Black',
        engine: '3.5L EcoBoost V6',
        horsepower: 450,
        description: 'The ultimate off-road performance truck. Built to conquer any terrain with extreme capability.',
        features: ['Fox Racing Shocks', 'Terrain Management System', 'Tailgate Step', 'B&O Sound System', '360-Degree Camera'],
        images: [
            'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format',
            'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format'
        ],
        isFeatured: true,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        make: 'Porsche',
        model: '911 Carrera',
        year: 2022,
        price: 119900,
        mileage: 8500,
        bodyType: 'Luxury',
        transmission: 'Automatic',
        fuelType: 'Gasoline',
        drivetrain: 'RWD',
        exteriorColor: 'GT Silver Metallic',
        interiorColor: 'Black/Bordeaux Red',
        engine: '3.0L Twin-Turbo Flat-6',
        horsepower: 379,
        description: 'Iconic sports car delivering exhilarating performance and timeless design. The epitome of driving pleasure.',
        features: ['Sport Chrono Package', 'PASM Suspension', 'Sport Exhaust', 'PCM with Navigation', 'Bose Sound System'],
        images: [
            'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800&auto=format',
            'https://images.unsplash.com/photo-1614200187524-dc4b892acf16?w=800&auto=format'
        ],
        isFeatured: true,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        make: 'Tesla',
        model: 'Model S Plaid',
        year: 2024,
        price: 94900,
        mileage: 2100,
        bodyType: 'Sedan',
        transmission: 'Automatic',
        fuelType: 'Electric',
        drivetrain: 'AWD',
        exteriorColor: 'Deep Blue Metallic',
        interiorColor: 'Black and White',
        engine: 'Tri Motor Electric',
        horsepower: 1020,
        description: 'Ultra-high-performance electric sedan. 0-60 mph in under 2 seconds. The quickest production car ever made.',
        features: ['Autopilot', 'Full Self-Driving Package', 'Carbon Fiber Spoiler', 'Premium Audio', 'Glass Roof'],
        images: [
            'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&auto=format',
            'https://images.unsplash.com/photo-1536700503339-1e4b06520771?w=800&auto=format'
        ],
        isFeatured: false,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        make: 'Jeep',
        model: 'Wrangler Rubicon',
        year: 2023,
        price: 52900,
        mileage: 14500,
        bodyType: '4x4',
        transmission: 'Automatic',
        fuelType: 'Gasoline',
        drivetrain: '4WD',
        exteriorColor: 'Sting-Gray',
        interiorColor: 'Black',
        engine: '2.0L Turbo I4',
        horsepower: 270,
        description: 'Legendary off-road capability meets modern comfort. Adventure awaits with the Rubicon package.',
        features: ['Removable Doors/Roof', 'Dana 44 Axles', 'Locking Differentials', 'Rock-Trac 4WD', 'Skid Plates'],
        images: [
            'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&auto=format',
            'https://images.unsplash.com/photo-1534650566718-ab629460f4eb?w=800&auto=format'
        ],
        isFeatured: false,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        make: 'Audi',
        model: 'Q8 Prestige',
        year: 2023,
        price: 78900,
        mileage: 9800,
        bodyType: 'SUV',
        transmission: 'Automatic',
        fuelType: 'Gasoline',
        drivetrain: 'AWD',
        exteriorColor: 'Mythos Black',
        interiorColor: 'Valcona Leather',
        engine: '3.0L TFSI V6',
        horsepower: 335,
        description: 'Striking coupe-style SUV with premium materials and cutting-edge technology throughout.',
        features: ['Virtual Cockpit Plus', 'Matrix LED Headlights', 'Bang & Olufsen 3D Sound', 'Massaging Seats', 'Air Suspension'],
        images: [
            'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&auto=format',
            'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&auto=format'
        ],
        isFeatured: false,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        make: 'Lexus',
        model: 'RX 350 F Sport',
        year: 2023,
        price: 56900,
        mileage: 11200,
        bodyType: 'SUV',
        transmission: 'Automatic',
        fuelType: 'Gasoline',
        drivetrain: 'AWD',
        exteriorColor: 'Atomic Silver',
        interiorColor: 'Rioja Red',
        engine: '3.5L V6',
        horsepower: 295,
        description: 'Refined luxury SUV with renowned reliability and comfort. F Sport package adds athletic styling.',
        features: ['Mark Levinson Audio', 'Panoramic View Monitor', 'Power Liftgate', 'Head-Up Display', 'Adaptive Variable Suspension'],
        images: [
            'https://images.unsplash.com/photo-1621929747920-f4f8b1d91e0c?w=800&auto=format',
            'https://images.unsplash.com/photo-1612825173281-9a193378527e?w=800&auto=format'
        ],
        isFeatured: false,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        make: 'Chevrolet',
        model: 'Corvette Stingray',
        year: 2024,
        price: 72900,
        mileage: 3200,
        bodyType: 'Luxury',
        transmission: 'Automatic',
        fuelType: 'Gasoline',
        drivetrain: 'RWD',
        exteriorColor: 'Torch Red',
        interiorColor: 'Jet Black',
        engine: '6.2L V8',
        horsepower: 490,
        description: 'Mid-engine American supercar. Stunning performance and aggressive styling at an incredible value.',
        features: ['Performance Exhaust', 'Magnetic Ride Control', 'GT2 Bucket Seats', 'Head-Up Display', 'Performance Data Recorder'],
        images: [
            'https://images.unsplash.com/photo-1600712242805-6c0a90f9c3e4?w=800&auto=format',
            'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format'
        ],
        isFeatured: false,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        make: 'Toyota',
        model: 'Camry XSE',
        year: 2024,
        price: 34900,
        mileage: 6500,
        bodyType: 'Sedan',
        transmission: 'Automatic',
        fuelType: 'Gasoline',
        drivetrain: 'FWD',
        exteriorColor: 'Supersonic Red',
        interiorColor: 'Black SofTex',
        engine: '2.5L 4-Cylinder',
        horsepower: 203,
        description: 'Reliable and stylish sedan with sporty XSE styling. Perfect blend of comfort and performance.',
        features: ['Adaptive Cruise Control', 'Lane Departure Warning', 'Apple CarPlay', 'Wireless Charging', 'Blind Spot Monitoring'],
        images: [
            'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&auto=format',
            'https://images.unsplash.com/photo-1619362280286-2f2c4b90d8b0?w=800&auto=format'
        ],
        isFeatured: false,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        make: 'Land Rover',
        model: 'Range Rover Sport',
        year: 2023,
        price: 89900,
        mileage: 15000,
        bodyType: 'SUV',
        transmission: 'Automatic',
        fuelType: 'Gasoline',
        drivetrain: 'AWD',
        exteriorColor: 'Santorini Black',
        interiorColor: 'Ebony/Pimento',
        engine: '3.0L Supercharged V6',
        horsepower: 355,
        description: 'Luxurious performance SUV with exceptional on-road dynamics and legendary off-road capability.',
        features: ['Meridian Sound System', 'Adaptive Dynamics', 'Configurable Ambient Lighting', 'Terrain Response 2', 'Sliding Panoramic Roof'],
        images: [
            'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&auto=format',
            'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&auto=format'
        ],
        isFeatured: false,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        make: 'Honda',
        model: 'Accord Sport',
        year: 2024,
        price: 32900,
        mileage: 4800,
        bodyType: 'Sedan',
        transmission: 'Automatic',
        fuelType: 'Gasoline',
        drivetrain: 'FWD',
        exteriorColor: 'Platinum White Pearl',
        interiorColor: 'Black',
        engine: '1.5L Turbo I4',
        horsepower: 192,
        description: 'Well-rounded sedan offering comfort, efficiency, and a sporty driving experience.',
        features: ['Honda Sensing', 'Dual-Zone Climate Control', 'Power Moonroof', '18-inch Wheels', 'Sport Pedals'],
        images: [
            'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&auto=format',
            'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&auto=format'
        ],
        isFeatured: false,
        isAvailable: true,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];
